# -*- coding: utf-8 -*-
"""DMV4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wL7lJ9ahu5DMToGWD6PzLuXay3Eae_o
"""

import pandas as pd
from scipy import stats

# Load dataset
df = pd.read_csv("/content/RealEstate_price.csv")

# Clean column names (spaces and special characters removed)
df.columns = df.columns.str.replace(' ', '_').str.replace(r'\W', '', regex=True)

# Example data cleaning display
print(df.head())

# Handle missing values (example: fill missing prices with the median)
df['Price'] = df['Price'].fillna(df['Price'].median())

# Calculating Z-scores for the 'Price' column to detect outliers
df['z_score'] = stats.zscore(df['Price'])

# Define a threshold for outliers (Z-score threshold: 3)
threshold = 3
outliers_mask = (df['z_score'] > threshold) | (df['z_score'] < -threshold)

# Extract and print outliers
outliers = df[outliers_mask]
print(outliers)

# Handle outliers (e.g., replace with median value)
df.loc[outliers.index, 'Price'] = df['Price'].median()

# Final dataset view after cleaning
print(df['Price'])